name:                raymarcher
version:             0.1.0.0
github:              "ryndubei/raymarcher"
license:             AGPL-3.0-or-later
author:              "ryndubei"
maintainer:          "114586905+ryndubei@users.noreply.github.com"
copyright:           "2023 ryndubei"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ryndubei/raymarcher#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- gloss-raster
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -optc-O3
- -optc-ffast-math

library:
  source-dirs: src

executables:
  raymarcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raymarcher

tests:
  raymarcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raymarcher
